/* @macrome
 * @generatefailed
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#171e775b8cdc9d10e6c6eba9868d7dd666820fec
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
throw new Error(`Error: Cannot find package 'babel-plugin-macros' imported from /home/stirl/bablr/language-uiua/lib/babel-virtual-resolve-base.js
    at __node_internal_ (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:224:9)
    at new NodeError (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:194:5)
    at packageResolve (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:908:9)
    at moduleResolve (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:937:20)
    at defaultResolve (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1007:15)
    at resolve (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1020:12)
    at tryImportMetaResolve (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/config/files/plugins.js:142:45)
    at resolveStandardizedNameForImport (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/config/files/plugins.js:164:19)
    at resolveStandardizedName (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/config/files/plugins.js:173:22)
    at loadPlugin (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/config/files/plugins.js:52:20)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/config/config-descriptors.js:140:16)
    at createDescriptor.next (<anonymous>)
    at step (/home/stirl/bablr/language-uiua/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/home/stirl/bablr/language-uiua/node_modules/gensync/index.js:291:5)
    at /home/stirl/bablr/language-uiua/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (/home/stirl/bablr/language-uiua/node_modules/gensync/index.js:43:15)
    at Function.all (/home/stirl/bablr/language-uiua/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at createDescriptors (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/config/config-descriptors.js:102:41)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/config/config-descriptors.js:99:17)
    at createPluginDescriptors.next (<anonymous>)
    at /home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/gensync-utils/functional.js:39:27
    at Generator.next (<anonymous>)
    at mergeChainOpts (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/config/config-chain.js:349:34)
    at mergeChainOpts.next (<anonymous>)
    at chainWalker (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/config/config-chain.js:316:14)
    at chainWalker.next (<anonymous>)
    at loadFileChain (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/config/config-chain.js:191:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/config/config-chain.js:108:31)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/config/partial.js:72:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/config/full.js:36:46)
    at loadFullConfig.next (<anonymous>)
    at Function.<anonymous> (/home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/transform-file.js:24:44)
    at Generator.next (<anonymous>)
    at step (/home/stirl/bablr/language-uiua/node_modules/gensync/index.js:269:25)
    at /home/stirl/bablr/language-uiua/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/stirl/bablr/language-uiua/node_modules/gensync/index.js:223:11)
    at /home/stirl/bablr/language-uiua/node_modules/gensync/index.js:50:45
    at step (/home/stirl/bablr/language-uiua/node_modules/gensync/index.js:287:14)
    at /home/stirl/bablr/language-uiua/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/stirl/bablr/language-uiua/node_modules/gensync/index.js:223:11)
    at /home/stirl/bablr/language-uiua/node_modules/gensync/index.js:189:28
    at /home/stirl/bablr/language-uiua/node_modules/@bablr/macrome-generator-bablr/node_modules/@babel/core/lib/gensync-utils/async.js:67:7
    at /home/stirl/bablr/language-uiua/node_modules/gensync/index.js:113:33
    at step (/home/stirl/bablr/language-uiua/node_modules/gensync/index.js:287:14)
    at /home/stirl/bablr/language-uiua/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/home/stirl/bablr/language-uiua/node_modules/gensync/index.js:223:11)
    at /home/stirl/bablr/language-uiua/node_modules/gensync/index.js:189:28
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)`);